<?php
use \Drupal\Core\Database\Database;

function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.hello':
      return '<p>' . t('Hello help page !!!!') . '</p>';
  }
}

function hello_cron() {

  \Drupal::messenger()->addMessage(t('Hello cron !!'));

  $purge_days_number = \Drupal::config('hello.settings')->get('purge_days_number');
  if ($purge_days_number !=0) {
    \Drupal::database()->delete('hello_user_statistics')
      ->condition('time', REQUEST_TIME - $purge_days_number * (24 * 3600), '<')
      ->execute();
  }
}

function hello_user_login(\Drupal\user\UserInterface $account) {

  // \Drupal::messenger()->addMessage(t('Welcom %name!', ['%name' => $account->getAccountName()]));

  $configRoles = \Drupal::config('hello.settings')->get('user_stat_roles');
  $userRoles = $account->getRoles();
  $diff = array_intersect($configRoles, $userRoles);

  //--
  if (count($diff) > 0) {
    \Drupal::database()->insert('hello_user_statistics')
      ->fields([
        'time' => REQUEST_TIME,
        'uid' => $account->id(),
        'action' => '1',
      ])
      ->execute();
  }
}

function hello_user_logout(\Drupal\Core\Session\AccountProxyInterface $account) {
  $configRoles = \Drupal::config('hello.settings')->get('user_stat_roles');
  $userRoles = $account->getRoles();
  $diff = array_intersect($configRoles, $userRoles);

  //--
  if (count($diff) > 0) {
    \Drupal::database()->insert('hello_user_statistics')
      ->fields([
        'time' => REQUEST_TIME,
        'uid' => $account->id(),
        'action' => '0',
      ])
      ->execute();
  }
}

function hello_user_delete(\Drupal\user\UserInterface $account) {
//--
  \Drupal::database()->delete('hello_user_statistics')
    ->condition('uid', $account->id())
    ->execute();
}


function hello_theme($existing, $type, $theme, $path) {
  return [
    'hello' => [
      'template' => 'hello',
      // 'variables' => ['data' => NULL],
      'variables' => ['userName' => NULL, 'countLog' => NULL],
    ],
  ];
}


function hello_form_user_admin_settings_alter(&$form, &$form_state, $form_id) {
  $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  unset($roles['anonymous']);
  $options = [];
  foreach ($roles as $role) {
    $options [$role->id()] = $role->label();
  }

  $form['user_stat'] = [
    '#type' => 'details',
    '#open' => 'TRUE',
    '#title' => t('Choose roles to track'),
    '#weight' => -1,

    'options' =>[
      '#type' => 'checkboxes',
      '#options' => $options,
      '#default_value' => \Drupal::config('hello.settings')->get('user_stat_roles'),
    ],
  ];

  $form['#submit'][] = 'hello_user_admin_settings_form_submit';
}

function hello_user_admin_settings_form_submit(&$form, &$form_state) {
  $options = $form_state->getValue('options');
  \Drupal::configFactory()->getEditable('hello.settings')
    ->set('user_stat_roles', $options)
    ->save();
}

function hello_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'node_article_form') {
    $form['revision_log']['#access']= FALSE;
  }
}
