<?php
use \Drupal\Core\Database\Database;

function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.hello':
      return '<p>' . t('Hello help page !!!!') . '</p>';
  }
}

function hello_cron() {

  \Drupal::messenger()->addMessage(t('Hello cron !!'));
}

function hello_user_login(\Drupal\user\UserInterface $account) {

  \Drupal::messenger()->addMessage(t('Welcom %name!', ['%name' => $account->getAccountName()]));

  //--
  \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'time' => REQUEST_TIME,
      'uid' => $account->id(),
      'action' => '1',
    ])
    ->execute();
}

function hello_user_logout(\Drupal\Core\Session\AccountProxyInterface $account) {
  //--
  \Drupal::database()->insert('hello_user_statistics')
    ->fields([
      'time' => REQUEST_TIME,
      'uid' => $account->id(),
      'action' => '0',
    ])
    ->execute();
}

function hello_user_delete(\Drupal\user\UserInterface $account) {
//--
  \Drupal::database()->delete('hello_user_statistics')
    ->condition('uid', $account->id())
    ->execute();
}
